apiVersion: v1
kind: ConfigMap

metadata:
  name: monitoring-config
  namespace: healthconnect

data:
  APP_PORT: "5000"
  LOG_LEVEL: "INFO"
  WARNING_THRESHOLD: "20"
  CRITICAL_THRESHOLD: "100"
  QUEUES: "REQUEST.Q,RESPONSE.Q,BOQ.REQUEST.Q,HCQM.DLQ"
  QMGR: "HCQM"
  MAX_HISTORY: "100"
  HISTORY_FILE: "queue_history.json"
