apiVersion: apps/v1
kind: Deployment

metadata:
  name: audit-service
  namespace: healthconnect

spec:
  replicas: 1

  selector:
    matchLabels:
      app: audit-service

  template:
    metadata:
      labels:
        app: audit-service

    spec:
      volumes:
      - name: audit-storage
        persistentVolumeClaim:
          claimName: audit-pvc

      containers:
      - name: audit-service
        image: healthconnect-ai-platform-audit-service:v1.0.2
        imagePullPolicy: IfNotPresent

        envFrom:
        - configMapRef:
            name: audit-config
        - secretRef:
            name: audit-secret

        ports:
        - containerPort: 5003

        volumeMounts:
        - name: audit-storage
          mountPath: /app/data



        readinessProbe:
          httpGet: 
            path: /health
            port: 5003
          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health
            port: 5003
          initialDelaySeconds: 15
          periodSeconds: 20

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"