apiVersion: apps/v1
kind: Deployment

metadata:
  name: lab-service
  namespace: healthconnect

spec:
  replicas: 1

  selector:
    matchLabels:
      app: lab-service
    
  template:
    metadata:
      labels:
        app: lab-service

    spec:
      volumes:
      - name: lab-storage
        persistentVolumeClaim:
          claimName: lab-pvc

      containers:
      - name: lab-service
        image: healthconnect-ai-platform-lab-service:v1.0.2
        imagePullPolicy: IfNotPresent

        envFrom:
        - configMapRef:
            name: lab-config
        - secretRef:
            name: lab-secret

        ports:
        - containerPort: 5002

        volumeMounts:
        - name: lab-storage
          mountPath: /app/data

        readinessProbe:
          httpGet: 
            path: /health
            port: 5002
          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 15
          periodSeconds: 20

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"