apiVersion: v1
kind: ConfigMap

metadata:
  name: ai-config
  namespace: healthconnect

data:
  APP_PORT: "5004"
  LOG_LEVEL: "INFO"
  OLLAMA_URL: "http://host.docker.internal:11434/api/generate"
  MONITOR_URL: "http://monitoring-service:5000/monitor/queues"
  MODEL_NAME: "qwen3:8b"